version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - cd src
      - npm install
      - cd ..
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file deploy.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - deploy.yaml